apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "istio-ratelimit.fullname" . }}
data:
  ingressgateway-ratelimit.yaml: |-
    domain: ingressgateway-ratelimit
    descriptors:
{{- range .Values.policies }}
  {{$key := .key }}
  {{$strategy := .strategy }}
  {{$limit_unit := .limit_unit }}
  {{$limit_requests := .limit_requests }}
  {{- range .paths }}
    {{$path := . }}
      - key: header_match
        value: "{{ $key }}_{{ $path.type }}_{{ $path.value }}"
        rate_limit:
          unit: {{ $limit_unit }}
          requests_per_unit: {{ $limit_requests }}
    {{- if $strategy }}
        descriptors:
      {{- range $strategy }}
         {{- if eq .type "header" }}
          - key: "header_{{ .value }}"
            rate_limit:
              unit: {{ .limit_unit }}
              requests_per_unit: {{ .limit_requests }}
         {{- end }}
         {{- if eq .type "ip"}}
          - key: remote_address
            rate_limit:
              unit: {{ .limit_unit }}
              requests_per_unit: {{ .limit_requests }}
          {{- end }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
