apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "istio-ratelimit.fullname" . }}
data:
  ingressgateway-ratelimit.yaml: |-
    domain: ingressgateway-ratelimit
    descriptors:
  {{- range .Values.rate_limits }}
  {{$name := .name }}
  {{- range .rules }}
      - key: header_match
        value: "{{ $name }}_{{ .path }}"
  {{- if .total}}
        rate_limit:
          unit: {{ .total.limit_unit }}
          requests_per_unit: {{ .total.limit_requests }}
  {{- end }}
  {{- if or .token .ip }}
        descriptors:
  {{- if .token}}
          - key: auth_token
            rate_limit:
              unit: {{ .token.limit_unit }}
              requests_per_unit: {{ .token.limit_requests }}
  {{- end }}
  {{- if .ip}}
          - key: header_match
            value: "no_auth"
            descriptors:
              - key: remote_address
                rate_limit:
                  unit: {{ .ip.limit_unit }}
                  requests_per_unit: {{ .ip.limit_requests }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
