apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "istio-ratelimit.fullname" . }}
  labels:
    {{- include "istio-ratelimit.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ratelimit.autoscaling.enabled }}
  replicas: {{ .Values.ratelimit.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "istio-ratelimit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ratelimit.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "istio-ratelimit.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.ratelimit.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ratelimit.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ratelimit.securityContext | nindent 12 }}
          image: "{{ .Values.ratelimit.image.repository }}:{{ .Values.ratelimit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ratelimit.image.pullPolicy }}
          command: ["/bin/ratelimit"]
          env:
            - name: LOG_LEVEL
              value: debug
            - name: REDIS_SOCKET_TYPE
              value: tcp
            - name: REDIS_URL
              value: {{ include "istio-ratelimit.fullname" . }}-redis-master:6379
            {{- if .Values.redis.usePassword }}
            - name: REDIS_AUTH
              value:  {{ .Values.redis.password }}
            {{- end }}
            - name: USE_STATSD
              value: "false"
            - name: RUNTIME_ROOT
              value: /data
            - name: RUNTIME_SUBDIRECTORY
              value: ratelimit
            - name: RUNTIME_IGNOREDOTFILES
              value: "true"
            - name: RUNTIME_WATCH_ROOT
              value: "false"
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 6070
          volumeMounts:
            - name: config-volume
              mountPath: /data/ratelimit/config
          resources:
            {{- toYaml .Values.ratelimit.resources | nindent 12 }}
      {{- with .Values.ratelimit.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ratelimit.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ratelimit.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "istio-ratelimit.fullname" . }}
