apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-ratelimit.fullname" . }}
  labels:
    {{- include "istio-ratelimit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc-port
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: http-debug
      port: 6070
      targetPort: 6070
      protocol: TCP
  selector:
    {{- include "istio-ratelimit.selectorLabels" . | nindent 4 }}
